name: Run Flow and Commit Output

on:
  push:
    branches:
      - test-sed
      - master
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write
jobs:
  run-flow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensures all branches are available

      - name: Run Flow
        run: |
          sed -i "s|<GOOGLE_CREDENTIALS_JSON>|$(echo "${{secrets.GOOGLE_CREDENTIALS_JSON}}" | sed 's/[&/\]/\\&/g')|g" appsettings.json

      - name: Configure Git
        run: |
          git config --global user.name "deenath400"
          git config --global user.email "deenath400@digital400.com"

      - name: Create or Switch to Output Branch
        run: |
          git checkout -B output-branch

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "Your Name"
          author_email: "your-email@example.com"
          message: "Automated: Run Flow Output"
          new_branch: output-branch
        env:
          GITHUB_TOKEN: ${{ secrets.YOUR_PAT_SECRET }}
