name: Test workflow

on:
  push:
    branches: ["master"]
    paths:
      - "be/**"
      - "fe/**"
  workflow_dispatch:

jobs:
  be:
    runs-on: self-hosted
    if: ${{ contains( github.event.head_commit.modified, 'be/') }}
    steps:
      - name: Be test
        run: |
          echo "BE change detected"

  fe:
    runs-on: self-hosted
    if: ${{ contains( github.event.head_commit.modified, 'fe/') }}
    steps:
      - name: Fe test
        run: |
          echo "FE change detected"
  job1:
    runs-on: self-hosted

    steps:
      - name: step1
        run: |
          echo "I'm in job 1 and and stage 1"

      - name: step2
        run: |
          echo "I'm in job 1 and and stage 2"

  job2:
    runs-on: self-hosted
    needs: job1
    environment:
      name: dev

    steps:
      - name: step1
        run: |
          echo "I'm in job 2 and and stage 1"

      - name: step2
        run: |
          echo "I'm in job 2 and and stage 2"

  job3:
    runs-on: self-hosted
    needs: job2
    environment:
      name: deploy

    steps:
      - name: step1
        run: |
          echo "I'm in job 2 and and stage 1"

      - name: step2
        run: |
          echo "I'm in job 2 and and stage 2"
