name: Test workflow

on:
  push:
    branches: ["test"]
  workflow_dispatch:

jobs:
  be:
    runs-on: ubuntu-latest
    steps:
      - name: Be test
        run: |
          echo "BE change detected ${{ secrets.test_val}"
          echo "BE change detected ${{ secrets.test_val2}"
          echo "BE change detected ${{ secrets.test_val3}"

  
