name: Custom-Check

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  check-task-link:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check if task link is present in comments
        uses: actions/github-script@v6
        with:
          script: |
            const comments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });

            const taskLinkRegex = /https:\/\/digital400.atlassian.net\/browse\/[A-Z]+-[0-9]+/;
            const hasTaskLink = comments.data.some(comment => taskLinkRegex.test(comment.body));

            if (hasTaskLink) {
              console.log("Task link found in comments.");
            } else {
              core.setFailed("No task link found in comments.");
            }
